export var __esModule: boolean;
export function ImageGrid(props: any): any;
export namespace ImageGrid {
    namespace propTypes {
        const dataImage: any;
        const sourceKey: any;
        const width: any;
        const colorLoader: any;
        const spaceSize: any;
        const containerStyle: any;
        const activeOpacity: any;
        const maximum: any;
        const onPressImage: any;
        const backgroundMask: any;
        const backgroundMaskVideo: any;
        const numberRemainStyle: any;
        const videoIconStyle: any;
        const videoKey: any;
        const videoURLKey: any;
        const conditionCheckVideo: any;
        const heightKey: any;
        const widthKey: any;
        const componentDelete: any;
        const onDeleteImage: any;
        const showDelete: any;
        const ratioImagePortrait: any;
        const ratioImageLandscape: any;
        const prefixPath: any;
        const backgroundColorKey: any;
        const ImageWrap: any;
    }
    namespace defaultProps {
        const dataImage_1: never[];
        export { dataImage_1 as dataImage };
        const colorLoader_1: string[];
        export { colorLoader_1 as colorLoader };
        const sourceKey_1: string;
        export { sourceKey_1 as sourceKey };
        const videoURLKey_1: string;
        export { videoURLKey_1 as videoURLKey };
        export { windowWidth as width };
        const spaceSize_1: number;
        export { spaceSize_1 as spaceSize };
        const activeOpacity_1: number;
        export { activeOpacity_1 as activeOpacity };
        const maximum_1: number;
        export { maximum_1 as maximum };
        const backgroundMask_1: string;
        export { backgroundMask_1 as backgroundMask };
        const backgroundMaskVideo_1: string;
        export { backgroundMaskVideo_1 as backgroundMaskVideo };
        const videoKey_1: string;
        export { videoKey_1 as videoKey };
        const conditionCheckVideo_1: boolean;
        export { conditionCheckVideo_1 as conditionCheckVideo };
        const heightKey_1: string;
        export { heightKey_1 as heightKey };
        const widthKey_1: string;
        export { widthKey_1 as widthKey };
        export function onPressImage_1(): void;
        export { onPressImage_1 as onPressImage };
        export const emptyImageSource: any;
        const showDelete_1: boolean;
        export { showDelete_1 as showDelete };
        export function onDeleteImage_1(): void;
        export { onDeleteImage_1 as onDeleteImage };
        const ratioImagePortrait_1: number;
        export { ratioImagePortrait_1 as ratioImagePortrait };
        const ratioImageLandscape_1: number;
        export { ratioImageLandscape_1 as ratioImageLandscape };
        const prefixPath_1: string;
        export { prefixPath_1 as prefixPath };
        const backgroundColorKey_1: string;
        export { backgroundColorKey_1 as backgroundColorKey };
        const ImageWrap_1: typeof _reactNative.Image;
        export { ImageWrap_1 as ImageWrap };
    }
}
export const ImageGridContext: any;
declare const windowWidth: number;
import _reactNative = require("react-native");
export {};
