export function ImageGrid(props: any): React.FunctionComponentElement<React.ProviderProps<{
    dataImage: never[];
    colorLoader: string[];
    sourceKey: string;
    videoURLKey: string;
    width: number;
    spaceSize: number;
    activeOpacity: number;
    maximum: number;
    backgroundMask: string;
    backgroundMaskVideo: string;
    videoKey: string;
    conditionCheckVideo: boolean;
    heightKey: string;
    widthKey: string;
    onPressImage: () => void;
    emptyImageSource: any;
    showDelete: boolean;
    onDeleteImage: () => void;
    ratioImagePortrait: number;
    ratioImageLandscape: number;
    prefixPath: string;
    backgroundColorKey: string;
    ImageWrap: typeof Image;
}>> | null;
export namespace ImageGrid {
    namespace propTypes {
        const dataImage: PropTypes.Validator<any>;
        const sourceKey: PropTypes.Requireable<string>;
        const width: PropTypes.Requireable<number>;
        const colorLoader: PropTypes.Requireable<any>;
        const spaceSize: PropTypes.Requireable<number>;
        const containerStyle: PropTypes.Requireable<any>;
        const activeOpacity: PropTypes.Requireable<number>;
        const maximum: PropTypes.Requireable<number>;
        const onPressImage: PropTypes.Requireable<(...args: any[]) => any>;
        const backgroundMask: PropTypes.Requireable<string>;
        const backgroundMaskVideo: PropTypes.Requireable<string>;
        const numberRemainStyle: PropTypes.Requireable<any>;
        const videoIconStyle: PropTypes.Requireable<any>;
        const videoKey: PropTypes.Requireable<string>;
        const videoURLKey: PropTypes.Requireable<string>;
        const conditionCheckVideo: PropTypes.Requireable<any>;
        const heightKey: PropTypes.Requireable<string>;
        const widthKey: PropTypes.Requireable<string>;
        const componentDelete: PropTypes.Requireable<PropTypes.ReactElementLike>;
        const onDeleteImage: PropTypes.Requireable<(...args: any[]) => any>;
        const showDelete: PropTypes.Requireable<boolean>;
        const ratioImagePortrait: PropTypes.Requireable<number>;
        const ratioImageLandscape: PropTypes.Requireable<number>;
        const prefixPath: PropTypes.Requireable<string>;
        const backgroundColorKey: PropTypes.Requireable<string>;
        const ImageWrap: PropTypes.Requireable<PropTypes.ReactComponentLike>;
    }
    namespace defaultProps {
        const dataImage_1: never[];
        export { dataImage_1 as dataImage };
        const colorLoader_1: string[];
        export { colorLoader_1 as colorLoader };
        const sourceKey_1: string;
        export { sourceKey_1 as sourceKey };
        const videoURLKey_1: string;
        export { videoURLKey_1 as videoURLKey };
        export { windowWidth as width };
        const spaceSize_1: number;
        export { spaceSize_1 as spaceSize };
        const activeOpacity_1: number;
        export { activeOpacity_1 as activeOpacity };
        const maximum_1: number;
        export { maximum_1 as maximum };
        const backgroundMask_1: string;
        export { backgroundMask_1 as backgroundMask };
        const backgroundMaskVideo_1: string;
        export { backgroundMaskVideo_1 as backgroundMaskVideo };
        const videoKey_1: string;
        export { videoKey_1 as videoKey };
        const conditionCheckVideo_1: boolean;
        export { conditionCheckVideo_1 as conditionCheckVideo };
        const heightKey_1: string;
        export { heightKey_1 as heightKey };
        const widthKey_1: string;
        export { widthKey_1 as widthKey };
        export function onPressImage_1(): void;
        export { onPressImage_1 as onPressImage };
        export const emptyImageSource: any;
        const showDelete_1: boolean;
        export { showDelete_1 as showDelete };
        export function onDeleteImage_1(): void;
        export { onDeleteImage_1 as onDeleteImage };
        const ratioImagePortrait_1: number;
        export { ratioImagePortrait_1 as ratioImagePortrait };
        const ratioImageLandscape_1: number;
        export { ratioImageLandscape_1 as ratioImageLandscape };
        const prefixPath_1: string;
        export { prefixPath_1 as prefixPath };
        const backgroundColorKey_1: string;
        export { backgroundColorKey_1 as backgroundColorKey };
        export { Image as ImageWrap };
    }
}
export const ImageGridContext: React.Context<{
    dataImage: never[];
    colorLoader: string[];
    sourceKey: string;
    videoURLKey: string;
    width: number;
    spaceSize: number;
    activeOpacity: number;
    maximum: number;
    backgroundMask: string;
    backgroundMaskVideo: string;
    videoKey: string;
    conditionCheckVideo: boolean;
    heightKey: string;
    widthKey: string;
    onPressImage: () => void;
    emptyImageSource: any;
    showDelete: boolean;
    onDeleteImage: () => void;
    ratioImagePortrait: number;
    ratioImageLandscape: number;
    prefixPath: string;
    backgroundColorKey: string;
    ImageWrap: typeof Image;
}>;
import { Image } from "react-native";
import React from "react";
import PropTypes from "prop-types";
declare const windowWidth: number;
export {};
